package event;

public enum EventType {
    ORDER_CREATED,
    EARLY_CANCELLATION,
    PREPARATION_STARTED,
    PREPARATION_DONE,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    DELIVERY_STARTED,
    DELIVERY_DELAYED,
    DELIVERY_COMPLETED
}
